clone:
	mkdir roles
	git clone https://github.com/derikz/server.seafile 	roles/server.seafile
	git clone https://github.com/sha2017/server.mariadb	roles/server.mariadb
	git clone https://github.com/sha2017/server.baseline	roles/server.baseline
	git clone https://github.com/sha2017/server.nginx-php7 roles/server.nginx.php7
